"""readd session date column with default value

Revision ID: 3a43c2494c1b
Revises: 1147bf9485a8
Create Date: 2020-10-28 20:30:21.882907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a43c2494c1b'
down_revision = '1147bf9485a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_session_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_date'))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
